vscode:
  extensions:
    - ms-vscode.cmake-tools@1.3.1:Yde58UUl5J9XpLmXM+Bqiw==
    - twxs.cmake@0.0.16:Ors8azcKj0Dx8fExuf6W6w==
    - austin.code-gnu-global@0.2.2:kA6Ik9bhcpAnHk4Q3DsKvw==
    - ms-vscode.cpptools@0.27.0-insiders3:Djj3Csw0GXjmueWAPWvTsg==
