pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - check-success=Build and Test
      - "#approved-reviews-by>=1"
      - base=dev
    actions:
      merge:
        method: merge
      delete_head_branch: {}
