notifications:
  email: false

language: c

services:
  - docker

env:
  - DOCKER_CONTAINER=thorshamster/squiddrone:latest

before_install:
  - docker pull ${DOCKER_CONTAINER}

script:
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./build.sh

after_script:
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./build_unittests.sh
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./generate_coverage.sh
  - docker run --env CI --env TRAVIS --env SHIPPABLE --env TRAVIS_COMMIT --env TRAVIS_JOB_NUMBER --env TRAVIS_PULL_REQUEST --env TRAVIS_JOB_ID --env TRAVIS_REPO_SLUG --env TRAVIS_TAG --env TRAVIS_BUILD_DIR=/usr/project/ --env TRAVIS_OS_NAME --env TRAVIS_BRANCH --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./upload_report_ci.sh
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./upload_codecov.sh

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "./squidDrone/build/SquidDrone.bin"
    skip_cleanup: true
    draft: true
    on:
      all_branches: true
  - provider: pages
    skip_cleanup: true
    local_dir: ./squidDrone/build/doc_doxygen/html
    github_token: $GITHUB_TOKEN
    on:
      branch: master
