dist: xenial

notifications:
  email: false

language: c

services:
  - docker

env:
  - DOCKER_CONTAINER=thorshamster/squiddrone:1.1

before_install:
  - docker pull ${DOCKER_CONTAINER}

script:
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./build.sh

after_script:
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./build_unittests.sh
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./generate_coverage.sh
  - printenv > .env_list
  - docker run --env-file .env_list --env TRAVIS_BUILD_DIR=/usr/project/ --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./upload_report_ci.sh
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker run $ci_env --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./upload_codecov.sh

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "./squidDrone/build/SquidDrone.bin"
    cleanup: true
    overwrite: true
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    local_dir: ./squidDrone/build/doc_doxygen/html
    github_token: $GITHUB_TOKEN
    on:
      branch: master
