notifications:
  email: false

language: c

services:
  - docker

env:
  - DOCKER_CONTAINER=thorshamster/squiddrone:latest

before_install:
  - docker pull ${DOCKER_CONTAINER}

script:
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./build.sh

after_script:
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./build_unittests.sh
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./generate_coverage.sh
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./upload_report_ci.sh
  - docker run --rm -v $(pwd):/usr/project ${DOCKER_CONTAINER} ./upload_codecov.sh

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    file: "./squidDrone/build/SquidDrone.bin"
    skip_cleanup: true
    draft: true
    on:
      all_branches: true
  - provider: pages
    skip_cleanup: true
    local_dir: ./squidDrone/build/doc_doxygen/html
    github_token: $GITHUB_TOKEN
    on:
      branch: master
