#!/usr/bin/env bash

# Apache License Version 2.0, January 2004
# https://github.com/codecov/codecov-bash/blob/master/LICENSE

set -e +o pipefail

add()
{
  if [ -z "$1" ];
  then
    return
  fi

  echo -n "-e $1 "
}

add "CI_BUILD_URL"
add "CI_BUILD_ID"
add "CI_JOB_ID"

if [ "$CI" = "true" ] && [ "$TRAVIS" = "true" ] && [ "$SHIPPABLE" != "true" ];
then
  add "CI"
  add "TRAVIS"
  add "SHIPPABLE"
  add "TRAVIS_BRANCH"
  add "TRAVIS_COMMIT"
  add "TRAVIS_JOB_NUMBER"
  add "TRAVIS_PULL_REQUEST"
  add "TRAVIS_JOB_ID"
  add "TRAVIS_REPO_SLUG"
  add "TRAVIS_TAG"
  add "TRAVIS_OS_NAME"

elif [ "$GITHUB_ACTIONS" != '' ]
then
  add "GITHUB_ACTION"
  add "GITHUB_REF"
  add "GITHUB_REPOSITORY"
  add "GITHUB_HEAD_REF"
  add "GITHUB_SHA"
  add "GITHUB_RUN_ID"

fi